export const COLORS = {
  INFO: "#057642",
  WARNING: "#FF9900",
  DANGER: "#CC3300",
  GREEN: "#13a05f",

  BLACK: "#000000",
  DARK: "#222222",

  WHITE: "#FFFFFF",
  GRAY: "#DDDDDD",

  BLUE: "#0a66c2",
  GREY: "#e8e8e8",
  BORDER: "#444444",

  TEXT_PRIMARY_LIGHT: "#000000",
  TEXT_SECONDARY_LIGHT: "#666666",

  TEXT_PRIMARY_DARK: "#FFFFFF",
  TEXT_SECONDARY_DARK: "#BBBBBB",

  BORDER_LIGHT: "#BBBBBB",
  BORDER_DARK: "#444444",

  HEADER_LIGHT: "#163D85",
  HEADER_DARK: "#222222",

  TRANSPARENT: "transparent"
};

export const THEMES = {
  LIGHT: {
    HEADER: COLORS.HEADER_LIGHT,
    BACKGROUND_PRIMARY: COLORS.WHITE,
    BACKGROUND_SECONDARY: COLORS.GREY,
    TEXT_PRIMARY: COLORS.TEXT_PRIMARY_LIGHT,
    TEXT_SECONDARY: COLORS.TEXT_SECONDARY_LIGHT,
    TAB: "#cccccc",
    BORDER: COLORS.BORDER_LIGHT,
    BUTTON_ACTIVE: COLORS.BLUE,
    BUTTON_INACTIVE: COLORS.BLUE
  },

  DARK: {
    HEADER: COLORS.HEADER_DARK,
    BACKGROUND_PRIMARY: COLORS.BLACK,
    BACKGROUND_SECONDARY: COLORS.DARK,
    TEXT_PRIMARY: COLORS.TEXT_PRIMARY_DARK,
    TEXT_SECONDARY: COLORS.TEXT_SECONDARY_DARK,
    TAB: "#111111",
    BORDER: COLORS.BORDER_DARK,
    BUTTON_ACTIVE: COLORS.BLUE,
    BUTTON_INACTIVE: COLORS.BLUE
  }
};
